packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@trpc/server": ^11.7.2
  better-auth: ^1.4.18
  "@types/express": ^5.0.1
  "@prisma/client": ^7.2.0
  "@trpc/tanstack-react-query": ^11.7.2
  "@trpc/client": ^11.7.2
  "@tanstack/react-query": ^5.90.12
  "@tanstack/react-form": ^1.28.0
  "@better-auth/expo": ^1.4.18
