packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/expo': ^1.4.18
  '@prisma/client': ^7.2.0
  '@tanstack/react-form': ^1.28.0
  '@tanstack/react-query': ^5.90.12
  '@trpc/client': ^11.7.2
  '@trpc/server': ^11.7.2
  '@trpc/tanstack-react-query': ^11.7.2
  '@types/express': ^5.0.1
  better-auth: ^1.4.18
  dotenv: ^17.2.2
  typescript: ^5
  zod: ^4.1.13

onlyBuiltDependencies:
  - '@prisma/engines'
  - argon2
  - esbuild
  - msw
  - prisma
  - sharp
